### PR TITLE
mark test/puppeteer as ESM

### LINKED ISSUE #24: double.js is unusable in node.js server environment
Having `"type": "module"` in `package.json` prevents usage of
`double.js` on server node.js with both --experimental-modules and
[`esm`](https://www.npmjs.com/package/esm) NPM package.

### PR DESCRIPTION
**Pull request by yanovich**
Having '"type": "module"' in 'package.json' prevents usage of
'double.js' on server node.js with both --experimental-modules and
'esm' NPM package.

Removing this flag from 'package.json' and renaming test module fixes
server side usability.

Closes #24

### CODE REVIEW

**Comment by munrocket** [comment]
Thanks!

**Comment by munrocket** [comment]
0.4.39 Successfully published.

**Comment by yanovich** [comment]
> Thanks!

You are welcome. Thanks for a great package! We have almost twice the precision with it compared to `long double` in C:
`$ ./spinner`
`3.1415926535897932384626433832795028841971`
`3.1415926535897932385128089594061862044327`

`double.js`:
`$ node app.js`
`3.1415926535897932384626433832795028841971`
`3.14159265358979323846264338327948e+0`

**Comment by munrocket** [comment]
Yep, use strings in constructor as described in readme.

**Pull request merged**
