### PR TITLE
fix (2**53+1).toExponential() with a test

### LINKED ISSUE #15: Fix bigInt print
For some reason (2**53+1).toExponential() gives wrong print but correct inside.
```
console.log(new Double('9007199254740992').sub(new Double('1')).toExponential());
//9.0071992547409932e+15
//Double {hi: 9007199254740992, lo: 1}
```
By the way working quickly with Int128 and printing it can be a good enhancement.

### PR DESCRIPTION
**Pull request by yanovich**
Fixing this brought out an error in second subtraction, which is
also fixed.

Closes #15

### CODE REVIEW

**Comment by munrocket** [comment]
Thank you for this patch!
Can you also bump version to 0.5.1?

**Comment by yanovich** [comment]
> Thank you for this patch!
> Can you also bump version to 0.5.1?

Done.

**Comment by munrocket** [comment]
Ty!

**Comment by yanovich** [comment]
Not sure why, but only one of two commits are merged.

**Comment by munrocket** [comment]
Yep, for some reason your very first commit not shown in github and I started to press `squash and merge`, as I understand this function join two commits into one.

Usually I am commit to someone else opensource projects and I am not so experienced to maintain your on. So my bad.

**Comment by yanovich** [comment]
> Yep, for some reason your very first commit not shown in github and I started to press `squash and merge`, as I understand this function join two commits into one.
> 
> Usually I am commit to someone else opensource projects and I am not so experienced to maintain your on. So my bad.

It's all right. I thought that changed to `package.json` were not merged, but they are.

**Pull request merged**
